/* just an example */
CREATE USER pdns WITH PASSWORD 'powerdns';
CREATE DATABASE powerdns WITH OWNER=pdns ENCODING='UTF8';
CREATE DATABASE powerdnsadmin WITH OWNER=pdns ENCODING='UTF8';
GRANT ALL PRIVILEGES ON DATABASE powerdns TO pdns;
GRANT ALL PRIVILEGES ON DATABASE powerdnsadmin TO pdns;
