replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

envs: {}

probes: {}

nodeSelector: {}

tolerations: []

affinity: {}

service:
  annotations: {}
  type: ClusterIP

ingress:
  enabled: false

image:
  pullPolicy: IfNotPresent
  repository: ''
  tag: ''
