apiVersion: v1
kind: Service
metadata:
  name: {{ include "powerdns.fullname" . }}
  labels:
    {{- include "powerdns.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    {{- include "powerdns.selectorLabels" . | nindent 4 }}
---
{{- if .Values.service_53 -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "powerdns.fullname" . }}-53
  labels:
    {{- include "powerdns.labels" . | nindent 4 }}
spec:
  ports:
    {{- toYaml .Values.service_53.ports | nindent 4 }}
  selector:
    {{- include "powerdns.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service_53.type }}
  externalTrafficPolicy: Local
{{- end -}}
