replicaCount: 1

image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/shipilovds/pdns-admin
  tag: 0.4.1

nameOverride: "powerdns-admin"
fullnameOverride: ""

envs: {}

ports:
  - name: wui
    containerPort: 8000
    protocol: TCP

probes:
  readinessProbe:
    httpGet:
      path: /
      port: wui
  livenessProbe:
    httpGet:
      path: /
      port: wui

service:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: wui

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: ns01.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ns01-example-com
      hosts:
        - ns01.example.com

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
